default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>

development:
  <<: *default
  database: lcg_quick_check_development

test:
  <<: *default
  database: lcg_quick_check_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
